### ISSUE TITLE
onUpdate doesn't seem to trigger

### ISSUE THREAD

**Issue by isumesh** [vinothpandian/react-sketch-canvas#1]
**Describe the bug**
onUpdate method doesn't seem to trigger

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinothpandian** [comment]
Can you please give me more information? It would be great if you can fill out the issue sheet with device, os, and browser information

**Comment by isumesh** [comment]
**Expected behavior**
onUpdate function should return the current paths on the canvas 

**Current behavior**
no data is returned. Looks like the function is not triggered.

**Desktop**
OS - macOS 10.15.2 (Catalina)
broswer - Google Chrome Version 80.0.3987.163

**Would help if the usage is shown in the documentation or the demo application.**

**Comment by isumesh** [comment]
any update @vinothpandian ?? using this library in one of my projects and stuck with out this functionality !! If you could guide me in the right direction, it would be helpful

**Comment by vinothpandian** [comment]
I just checked. I removed onUpdate functionality in the last release because of few bugs. I am planning to rewrite the library anyway next month, so I will add it back.

**Comment by isumesh** [comment]
Ohk. I want the user canvas data as soon as they release their mouse so that i can share that path to other users canvas.
Is there a way i can achieve this functionality using your library right now ?

**Comment by vinothpandian** [comment]
Yes.  For now, you can import the Canvas module directly. Then you can hook the event handlers get updated paths.

Check the [index.js](https://github.com/vinothpandian/react-sketch-canvas/blob/master/src/index.js) in src directory
