### ISSUE TITLE
default value of `allowOnlyPointerType`  is `'pen'`

### ISSUE THREAD

**Issue by igakim** [vinothpandian/react-sketch-canvas#10]
**Describe the bug**
Documentation says that default value of `allowOnlyPointerType`  is `'all'`, but it's `'pen'`

**Expected behavior**
default value is `all`

TY, for nice tool!

**Comment by vinothpandian** [comment]
Thank you for pointing it out!

I am planning for a big update with smooth sketching logic from Jan Hug's Lazy Brush. I will fix it with that

**Comment by vinothpandian** [comment]
Fixed in version 5.3.1
