### ISSUE TITLE
[Chrome and Safari for iPad] - Export base64 with exportImage only shows the top 30% of the stokes

### ISSUE THREAD

**Issue by juanEllaMD** [vinothpandian/react-sketch-canvas#11]
**Describe the bug**
I was testing drawing something on Chrome for iPad and saw this.
After drawing a stroke, export as "png" with exportImage. The Base64 image only shows the top 30% of the strokes, but a vertical line that covers all of the canvas was draw. This is happening on the playground and in my personal project.

**To Reproduce**
1_ Open Chrome or Safari on iPad
2_ Go to https://vinoth.info/react-sketch-canvas/?path=/story/full-demo--sketch-canvas
3_ Draw something vertically across the canvas
4_ export as image (exportImage)

**Expected behavior**
Should see the entire stroke

**Actual behavior**
Only the top 30% of the stroke is visible

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad 5th generation
 - OS: iOS 14
 - Browser: Safari and Chrome

**Comment by juanEllaMD** [comment]
Sorry for my broken english and thanks in advance. Regards.

**Comment by vinothpandian** [comment]
Hi @juanEllaMD,

Thank you for the description of the bug. However, I do not have the hardware to recreate the bug. I will attempt to fix it.

If you need it urgently, then as a workaround you can export the "svg" instead using `exportSvg` function. Then convert this svg to png using canvg or any other library.

**Comment by vinothpandian** [comment]
Fixed in version 5.3.0

@juanEllaMD Please check it in your device and close this issue

**Comment by vinothpandian** [comment]
Closing this issue as it is fixed. Please reopen if it still persists
