### ISSUE TITLE
Feature to block the user of drawing at the canvas

### ISSUE THREAD

**Issue by JoaoGuiMB** [vinothpandian/react-sketch-canvas#125]
I would like to know if there is already a feature that does not allow the user to draw on the canvas. For example, a ```canDraw``` property at ```ReactSketchCanvas``` that avoids the user to draw on it?

I'm developing a drawing game and I want to only allow the user to draw when it's his turn. I already kinda implemented it while I was checking the code, if this feature does not exist, I can add it.

**Comment by vinothpandian** [comment]
Fixed this. Will release it with v7.0.0.next.4

**Comment by vinothpandian** [comment]
Released this with [v7.0.0.next.4](https://github.com/vinothpandian/react-sketch-canvas/releases/tag/react-sketch-canvas%407.0.0-next.4)
