### ISSUE TITLE
No Stroke Found!

### ISSUE THREAD

**Issue by jnoren1** [vinothpandian/react-sketch-canvas#133]
It took me longer than I care to admit to figure that the warning "No Stroke Found!" is an intended notification on first load. Not a bug.

**Describe the solution you'd like**
Can that warning be optionally turned off?  In development mode it is killing the console with an impressive stack trace.

**Describe alternatives you've considered**
I'm not entirely sure what purpose the warning serves other than to notify the console that the back button won't work and that nothing should be drawn on the screen....

I'm open to other solutions.

**Comment by maxcmoi89** [comment]
Same :(

**Comment by rtrevisanlectra** [comment]
I agree!

**Comment by webkuzya** [comment]
Same :(
console with an impressive stack trace
`No stroke found!`

**Comment by skiffter1337** [comment]
Same!

**Comment by yneskladovae** [comment]
I have the same problem!

**Comment by vinothpandian** [comment]
Fixed with [v7.0.0-next.0](https://github.com/vinothpandian/react-sketch-canvas/releases/tag/react-sketch-canvas%407.0.0-next.0)

**Comment by pointful-dave** [comment]
This does not seem to be fixed in v7.0.0-next.5
Also: what is the plan for releasing 7.0.0?
