### ISSUE TITLE
[feature request] resize exportImage

### ISSUE THREAD

**Issue by rickythink** [vinothpandian/react-sketch-canvas#134]
**Is your feature request related to a problem? Please describe.**
the export image size of `exportImage`  may not be the exact width / height of canvas, it should accept user settings

**Describe the solution you'd like**
```
ref.exportImage('png, { width: 120, height: 120 })
```

**Describe alternatives you've considered**
right now we can only do it outside the lib

**Comment by vinothpandian** [comment]
Fixed in [7.0.0-next.3](https://github.com/vinothpandian/react-sketch-canvas/releases/tag/react-sketch-canvas%407.0.0-next.3)
