### ISSUE TITLE
Short consecutive strokes do not work with iPad OS and Apple Pencil.

### ISSUE THREAD

**Issue by dninomiya** [vinothpandian/react-sketch-canvas#139]
When I make consecutive short strokes on the iPad using the Apple Pencil, the second stroke does not register. I suspect it's because the standard iOS magnifying glass feature is taking over the input. As a workaround to disable the magnifying glass, I implemented [preventDefault](https://stackoverflow.com/questions/75628788/disable-double-tap-magnifying-glass-in-safari-ios) in onTouchStart and onPointerDown, but it didn't work (it seems it wasn't disabled).

Is there a solution?"

**To Reproduce**
1. Go to [Demo](https://vinoth.info/react-sketch-canvas/)
2. When drawing dots consecutively, the second dot cannot be drawn. (with Apple Pencil)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- iPadOS 16.6
- Apple Pencil 1

https://github.com/vinothpandian/react-sketch-canvas/assets/5842851/26e802f0-f87a-411a-9535-002cabfbdee5

**Comment by dninomiya** [comment]
I have resolved this issue with the latest version of Safari, so I will close it.

**Comment by Tomerkakou** [comment]
@dninomiya  its still happens to me any fixes you can suggest?

**Comment by Tomerkakou** [comment]
> [@dninomiya](https://github.com/dninomiya) its still happens to me any fixes you can suggest?

After checking almost every possibility got the answer , setting scribble off in Apple Pencil settings .
Hope it will help someone 🥲
