### ISSUE TITLE
Bump immer version to at least 8.0.1

### ISSUE THREAD

**Issue by thongteav** [vinothpandian/react-sketch-canvas#18]
**Describe the bug**
A Prototype Pollution vulnerability affecting immer version 7.0.9 has been raised by Snyk when trying to npm install react-sketch-canvas.

**Expected behavior**
Would be nice to update the immer dependency version to at least 8.0.1 or the latest version 9.0.1.

Thanks.

**Comment by vinothpandian** [comment]
Done
