### ISSUE TITLE
Canvas path edges are not smooth when drawn using pencil

### ISSUE THREAD

**Issue by isumesh** [vinothpandian/react-sketch-canvas#2]
**Describe the bug**
When we draw or write something on the canvas using an apple pencil the paths are not crisp.
Whereas on the web its fine.
Image attached here
<img width="536" alt="Screenshot 2020-04-29 at 10 55 30 PM" src="https://user-images.githubusercontent.com/63849019/80629055-ebc85880-8a6f-11ea-8baf-b16fb1f9f0c7.png">

**To Reproduce**

**Expected behavior**
Things drawn or written on the canvas should be crisp.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ipadOS 13
 - Browser -  chrome for ipad

**Additional context**

**Comment by vinothpandian** [comment]
Planning to add polyfill to support pointer events in iOS. Hope that solves it

**Comment by isumesh** [comment]
hi thanks for the prompt response.
as i mentioned earlier, i m using this library in a project and this functionality is critical. can u guide me how i can add this now ?

**Comment by vinothpandian** [comment]
This should solve the issue. [PEP with react](https://github.com/jquery/PEP#using-pep-with-react).

If this doesn't then the bezier command function of this library must be changed. This function is in src/paths.js

**Comment by vinothpandian** [comment]
Updated this in the last version 5.0.1

Check whether this fixes your issue.

**Comment by vinothpandian** [comment]
Closed due to inactivity
