### ISSUE TITLE
Select mode feature

### ISSUE THREAD

**Issue by potamir** [vinothpandian/react-sketch-canvas#26]
**I'd like to suggest for select mode, so you can select specific draw and drag around or copy paste it**.  Maybe it can come along with basic shape feature like rectangle or circle etc. I'm not really good with canvas, so it'll be really helpful.

_Thank You_

**Comment by potamir** [comment]
Oh btw, tyvm for this package. It's already really helpful at the first place:)

**Comment by vinothpandian** [comment]
I did not implement these features to keep the focus on the freehand sketching aspect alone. There are many good libraries that have these features. A few of my favourites are [konvajs](https://konvajs.org/) & [Fabricjs](http://fabricjs.com/). You can take a look at them
