### ISSUE TITLE
erase mode overlaying white color on the background

### ISSUE THREAD

**Issue by lkevinzc** [vinothpandian/react-sketch-canvas#35]
**Is your feature request related to a problem? Please describe.**
As the following image shows, the current `eraseMode` is overlaying white color on the background image, which in my opinion should not be the real "erase". Could it be possible to make the svg just empty on that region when doing erase?
![image](https://user-images.githubusercontent.com/38581401/130004811-27021136-0ed2-4696-baf5-e08204f294bc.png)

**Describe the solution you'd like**
The while color region in the above image should be recovered and display the background.

**Describe alternatives you've considered**
Not yet

**Additional context**
N.A.

Not sure whether this makes sense, please advise! Thank you in advance!

**Comment by vinothpandian** [comment]
Hey @lkevinzc ,

In it's current form, it is tricky to implement this without losing performance. Basically I'll have to find and remove the colliding points in the previous path. I can take a look at it may in a month or two.

**Comment by lkevinzc** [comment]
Hi @vinothpandian , thanks for the response!

Yep sure. I am thinking that whether we can set the transparency value for the brush? If yes, then maybe simply putting [0, 0, 0, 0] values for `erase` brush will do. And for normal brush, we can put [r, g, b, 255]. Please advise if this could be possible. Thank you so much!

**Comment by vinothpandian** [comment]
Unfortunately, that wouldn't work as if the eraser stroke is transparent, it will show the underlying stroke too.

**Comment by lkevinzc** [comment]
I mean maybe to overwrite the previous stroke by a transparent stroke? Transparent because it can show the underlying background image.

**Comment by vinothpandian** [comment]
Hi @lkevinzc,

Good news. I found a solution for this issue using the mask element in SVG. I will roll out an update today or tomorrow.

**Comment by lkevinzc** [comment]
Hi @vinothpandian ,

Glad to know this! Thank you so much~
