### ISSUE TITLE
Base64 String Image in background is distorted

### ISSUE THREAD

**Issue by skoolguy** [vinothpandian/react-sketch-canvas#58]
**Describe the bug**
When we provide a base64 encoded string of an image to the prop backgroundImage, the background image is not showing up properly, it is distorted and with very small height(not filling the canvas and not recognizable)

**To Reproduce**
```
                            <ReactSketchCanvas
                                ref={ canvasRef }
                                style={{
                                    border: '0.0625rem solid #9c9c9c',
                                    borderRadius: '0.25rem'
                                }}
                                height={ naturalHeight }
                                width={ naturalWidth }
                                strokeWidth={ 4 }
                                strokeColor="red"
                                backgroundImage={ base64String }
                                exportWithBackgroundImage
                            />
```

**Expected behavior**
The background image should be displayed in the canvas with the height and width of the actual image

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : Chrome
 - Version : 96.0.4664.110 (Official Build) (x86_64)

**Additional context**
When the sketched image is downloaded, it is getting downloaded correctly.

**Comment by IslamIv** [comment]
did you find a solution yet?

**Comment by skoolguy** [comment]
No, I tried to fix it but could not. And then I opened the issue but nobody has picked it up yet

**Comment by vinothpandian** [comment]
Thanks for raising the issue. I'm look into this next week.
