### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by davidlimajet** [vinothpandian/react-sketch-canvas#6]
**Describe the bug**
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

**To Reproduce**
1. npm i react-sketch-canvas
2. import ReactSketchCanvas from "react-sketch-canvas";
3. Canvas render

**Expected behavior**
I have followed the installation steps and I have had errors in the component rendering.

**Screenshots**
Attached screenshots of console errors
![image](https://user-images.githubusercontent.com/53547126/92554437-fa4b2b80-f22a-11ea-8c4a-271ad8a99075.png)
![image](https://user-images.githubusercontent.com/53547126/92554066-11d5e480-f22a-11ea-9f9e-68ac284815bd.png)
![image](https://user-images.githubusercontent.com/53547126/92554135-3fbb2900-f22a-11ea-8baa-211605576e7d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85

I appreciate your help

**Comment by vinothpandian** [comment]
Can you please try importing using the following code?

`import { ReactSketchCanvas } from "react-sketch-canvas";`

**Comment by davidlimajet** [comment]
Perfect, thank you very much
