### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by suresheprm** [vinothpandian/react-sketch-canvas#61]
When i submit i got this error

Error:
canvas {current: ReactSketchCanvas}current: null[[Prototype]]: Object
Uncaught (in promise)

**Comment by vinothpandian** [comment]
@suresheprm Can you provide more info or some reproducable example in [codesandbox](https://codesandbox.io/)? It would be great if you can also fill up the issue template.

**Comment by vinothpandian** [comment]
Cannot reproduce this issue. Please reopen if someone else faces this again.
