### ISSUE TITLE
No-renders-for-reactapp

### ISSUE THREAD

**Issue by VarunJoshihere** [vinothpandian/react-sketch-canvas#68]
I ran the installation and implementation as shown in the underlying docs, though i wasnt able to run it, my react app port 3000 just freezes the moment i add ReactSketchCanvas

**Comment by vinothpandian** [comment]
@VarunJoshihere Can you provide more info or some reproducible example in [codesandbox](https://codesandbox.io/)? It would be great if you can also fill up the issue template.

**Comment by vinothpandian** [comment]
Cannot reproduce this issue. Please reopen if someone else faces this again.
