### ISSUE TITLE
TypeScript types are missing from dist folder!

### ISSUE THREAD

**Issue by oxodesign** [vinothpandian/react-sketch-canvas#7]
**Describe the bug**
Types (index.d.ts) is missing from dist folder on latest release

**To Reproduce**
1. Run `npm i react-sketch-canvas` to install on a TS project
2. Run it, it will complain that types are not being found

**Comment by Kastango** [comment]
I had the same problems, when upgrading to the latest version my project broke because of the typing

**Comment by vinothpandian** [comment]
Fixed in v5.1.2
