### ISSUE TITLE
Want to use tools like rectangle, circle and text

### ISSUE THREAD

**Issue by Deep-Menpara** [vinothpandian/react-sketch-canvas#80]
How can I implement tools like rectangle and text using this library.

**Comment by vinothpandian** [comment]
I was planning to keep it as a simple sketching tool.

**Comment by josh-stillman** [comment]
@vinothpandian Fair!  Thanks for the great library, it was really useful on the first iteration of our feature!

We ended up switching to [react-konva](https://github.com/konvajs/react-konva) for more advanced markup functionality like text, shapes, arrows, etc.

**Comment by sawasawasawa** [comment]
Hi @vinothpandian I might be interested in adding simple shapes (rect, circle, arrow) and text. Did you have any API in mind or rather waiting for suggestions?

**Comment by vinothpandian** [comment]
I would like to keep ReactSketchCanvas as a simple sketching tool. I recommend [react-konva](https://github.com/konvajs/react-konva) for advanced functionality.
