### ISSUE TITLE
Question: callback similar to onUpdate that is not triggered everytime

### ISSUE THREAD

**Issue by isumesh** [vinothpandian/react-sketch-canvas#9]
**Describe the bug**
Is there a callback function that is triggered when the user is done drawing on the canvas.

**To Reproduce**
onUpdate callback function is triggered everytime

**Expected behavior**
a callback that is triggered when the user is done drawing the path

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinothpandian** [comment]
There is no ready-to-use callback, but you can use any one of the following methods.

### Method 1 (recommended):
Add a listener to the `pointerup` event of the canvas. This is fired whenever the user stops sketching a stroke.

### Method 2:
You can set the `withTimestamp` prop of the ReactSketchCanvas component. This adds an `endTimestamp` to each stroke in the paths you receive from `onUpdate` callback. The user stopped sketching whenever you receive this timestamp. This also allows you to distinguish between 'erase complete' and 'stroke complete'.

Hope this helps!
